image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  
  - java -jar ./artifacts/app-ibank.jar  &
  - chmod +x gradlew


build_script:
  - java -jar app-ibank.jar -P:profile=test
  - ./gradlew test --info -Dselenide.headless=true

